---
title: "GOV.UK taxonomy interactive explorer [WIP]"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
# Call packages
library(flexdashboard)  # creates the dashboard framework
library(readr)  # reading data
library(collapsibleTree) # https://adeelk93.github.io/collapsibleTree/
library(DT)
library(dplyr)

# Read pre-prepared data from file 01_flatten-hierarchy.R
hierarchy_flat <- read_csv("output/hierarchy_flat.csv")

# Create interactive tree to be called in a later chunk
tree <- collapsibleTree(
  hierarchy_flat,  # input data frame
  hierarchy = paste0("level", 1:5),  # columns containing hierarchy
  root = "GOV.UK",  # name for root node
  zoomable = FALSE,  # zoom in and out of the plot
  fill = "#005ea5"  # set to GOV.UK default for now
)

taxon_links <- read_csv("data/taxon_links.csv") %>% 
  mutate(URL = paste0('<a  target=_blank href=', taxon_link, '>', taxon_link,'</a>')) %>% 
  select(Name = taxon_name, URL) %>% 
  arrange(Name)
```

Tree {data-icon="ion-stats-bars"}
=====================================  

Column {data-width=650}
-----------------------------------------------------------------------

### Explore the tree

```{r tree}
tree  # render the interactive tree
```

Table {data-orientation=rows data-icon="ion-grid"}
===================================== 

Column {data-width=350}
-----------------------------------------------------------------------

### Get topic page on GOV.UK

```{r}
datatable(
  taxon_links,
  escape = FALSE,
  style = "bootstrap",
  class = "compact",
  width = "100%",
  extensions = c("Scroller"),
  options = list(
    deferRender = TRUE,
    scrollY = 300,
    scroller = TRUE
  )
)
```